module.exports = {
    personMet: "#Person_Mets_FIV_Residence_Verification_0",
    relation: "#Relation_Applicants_FIV_Residence_Verification_0",
    dependents: "#Number_of_Dependent_FIV_Residence_Verification_0",
    noOfFamilyMembers: "#No_of_Family_Member_FIV_Residence_Verification_0",
    noOfEarningMembers: "#No_of_Earning_Member_RES_FIV_Residence_Verification_0",
    spouseWorkingNo: "#Spouse_Working_Res_FIV_Residence_Verification_01",
    spouseWorkingYes: "#Spouse_Working_Res_FIV_Residence_Verification_02",
    spouseWorkingDesc: "#Spouse_Working_Description_RES_FIV_Residence_Verification_0",
    yearsCity: "#Years_IN_CITY_RES_FIV_Residence_Verification_0",
    yearsResidence: "#Years_At_Residence_RES_FIV_Residence_Verification_0",
    addressConfirmYes: "#Address_Confirm_Flag_RES_FIV_Residence_Verification_02",
    addressConfirmNo: "#Address_Confirm_Flag_RES_FIV_Residence_Verification_01",
    earningMembers: "#Earning_Members_RES_FIV_Residence_Verification_03", // default "Father"
    dateTimeVisit: "#Date_Time_Visit_Res_FIV_Residence_Verification_0",
    latitude: "#Residence_Veri_Latitude_FIV_Residence_Verification_1",
    longitude: "#Residence_Veri_Longitude_FIV_Residence_Verification_1",
    // residenceStatusOwned: "#Residence_Status_RS_FIV_Residence_Verification_23",
    // residenceStatusSelfOwned: "#Residence_Status_RS_FIV_Residence_Verification_29",
    permanentAddress: "#Permanent_Address_Res_FIV_Residence_Verification_3",
    contactPerson: "#Contact_Person_Res_FIV_Residence_Verification_3",
    telephoneNumber: "#Telephone_Number_Res_FIV_Residence_Verification_3",
    rentPerMonth: '#Rent_Per_Month_Res_FIV_Residence_Verification_3',
    // areaInSqFt: "#Area_RES_FIV_Residence_Verification_31",
    easeOfLocateEasy: "#Ease_of_Locate_Address_Res_FIV_Residence_Verification_52",
    easeOfLocateDifficult: "#Ease_of_Locate_Address_Res_FIV_Residence_Verification_51",
    landmark: "#Verifiers_Observation_Landmark_Res_FIV_Residence_Verification_5",
    typeOfResidence: "#Type_Of_Residence_FIV_Residence_Verification_53",
    areaOfResidenceNegative: "#Area_Of_Residence_FIV_Residence_Verification_51",
    residenceConstructionPukka: "#Residence_Construction_FIV_Residence_Verification_51",
    commentOnExteriorAverage: "#Comment_on_Exterior_FIV_Residence_Verification_51",
    interiorAverage: "#Interior_FIV_Residence_Verification_51",
    nameOfPerson: "#Name_Of_Person_Res_FIV_Residence_Verification_6",
    applicantDetailsConfirmedYes: "#Applicant_Details_Confirmed_Res_FIV_Residence_Verification_62",
    applicantDetailsConfirmedNo: "#Applicant_Details_Confirmed_Res_FIV_Residence_Verification_61",
    negativeFeedback: "#Negative_Feedback_If_Any_FIV_Residence_Verification_6",
    residenceLockedYes: "#Residence_Locked_FIV_Residence_Verification_62",
    residenceLockedNo: "#Residence_Locked_FIV_Residence_Verification_61",
    verifierName: "#Verifier_Name_Signature_Res_FIV_Residence_Verification_8",
    cpvResultPositive: "#CPV_Result_Res_FIV_Residence_Verification_82",
    cpvResultNegative: "#CPV_Result_Res_FIV_Residence_Verification_81",
    verifierComments: "#Verifier_comment_Res_FIV_Residence_Verification_8",
    cpvRejectedReasons: "#CPV_Rejected_For_Following_Reason_FIV_Residence_Verification_8",
    noOfAttempts: "#noOfAttempts",
    verificationAgent: "#field_investigation_entry_verification_agent",
    verificationResult: "#field_investigation_entry_vo_verificationResult",
    firstPartSave: "#dynSave",
    dynamicFormSave: "#saveDynamicFormBtn",
    saveAndProceed: "#move_to_next_stage_fiv",
    remarks1: '#remarks_res_FIV_Residence_Verification_9',
    remarks2: '#field_investigation_entry_remarks',
};